server:
  port: 8081

spring:
  application:
    name: AUTH-SERVICE

  datasource:
    url: jdbc:mysql://localhost:3306/oms
    username: root
    password: 12345678
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

jwt:
  secret: 6pA9qM8xL2vR5nT7uW1yZ4cF8hJ3kN6sQ0eD2gH9mP7xB4rV8sN5dK1qL7mX2aH9jF
  access-token-expiration: 3600000
  refresh-token-expiration: 604800000